import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getStoryblokApi } from "@storyblok/react";

export default function Home(props) {
  const { story } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>{story.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>{story.content.title}</h2>
        <h5>{story.content.description}</h5>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  let slug = "landing-page";

  let sbParams = {
    version: "draft", // or 'published'
  };

  const storyblokApi = getStoryblokApi();
  let { data } = await storyblokApi.get(`cdn/stories/${slug}`, sbParams);

  return {
    props: {
      story: data ? data.story : false,
      key: data ? data.story.id : false,
    },
    revalidate: 3600,
  };
}
